String baseUrl = 'https://amoremio.lared.lat/apis/services/';
String baseUrlImage = 'https://amoremio.lared.lat/';

String getGender = '${baseUrl}get_genders';
String signUp = '${baseUrl}signup';
String logIn = '${baseUrl}login';
String forgotpass = '${baseUrl}forgot_password';
String verifyCode = '${baseUrl}verify_code';
String resetPassword = '${baseUrl}reset_password';
String changePassword = '${baseUrl}change_password';
String getusersProfile = '${baseUrl}get_users_profile';
String uploadProfile = '${baseUrl}users_upload_profile';
String uploadAvatars = '${baseUrl}upload_avatars';
String getusersavatars = '${baseUrl}get_users_avatars';
String editProfile = '${baseUrl}users_edit_profile';
String getInterests = '${baseUrl}get_interests_tags';
String userDiscover = '${baseUrl}users_discover';
String userblockedunblocked = '${baseUrl}blocked_unblocked_user';
String userliked = '${baseUrl}users_likes';
String getuserblocked = '${baseUrl}get_blocked_users';
String getuserliked = '${baseUrl}get_users_liked';
String getuserlikedme = '${baseUrl}get_users_liked_you';
String getusermatch = '${baseUrl}users_matches';
String deactivateUser = '${baseUrl}deactivate_user';
String deleteUser = '${baseUrl}delete_user';
String deleteAvator = '${baseUrl}delete_avatars';
String searchUsers = '${baseUrl}search_users';
String getChatmessages = '${baseUrl}get_users_chat_messages';
String sendChatmessages = '${baseUrl}users_send_chat_messages';
String getChats = '${baseUrl}get_users_chat';
String getUserstories = '${baseUrl}get_free_users_stories';
String getstories = '${baseUrl}stories_filter';
String usersstorieslikes = '${baseUrl}users_stories_likes';
String getuserallstories = '${baseUrl}get_users_stories';
// String getuserallstories = '${baseUrl}get_user_all_stories';
String getPaidstories = '${baseUrl}get_paid_users_stories';
String createStories = '${baseUrl}create_stories';
String usersFilter = '${baseUrl}users_filter';
String userExploreStories = '${baseUrl}get_user_all_stories';

/// Define App ID and Token
const appId = '92c5fa7f04fe4787a4706ffaa553d7a2';
const token = '007eJxTYLh6rsIl8uWqrqg5dwM2/lfZfP6800rOtRcr94oU72h9tOWcAoOlUbJpWqJ5moFJWqqJuYV5oom5gVlaWmKiqalxinmikfgLzbSGQEYG5ZAtrIwMjAwsQAziM4FJZjDJAibZGHIz8x0LChgYABXvJX0=';
